name: grocery_store
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  page_indicator: ^0.4.1
  ecommerce_kit: ^0.0.2
  velocity_x: ^3.6.0
  auto_size_text: ^3.0.0
  readmore: ^2.2.0
  curved_navigation_bar: ^1.0.3
  another_stepper: ^1.2.2
  timeline_tile: ^2.0.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/
  #   - images/a_dot_ham.jpeg

   
  # fonts:
  #   - family: MaterialIcons
  #     fonts:
  #       - asset: fonts/MaterialIcons-Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
